#ifndef COMPONENTS_RTSHADERSYSTEM_INCLUDE_OGRERTSHADERCONFIG_H_
#define COMPONENTS_RTSHADERSYSTEM_INCLUDE_OGRERTSHADERCONFIG_H_

/* #undef RTSHADER_SYSTEM_BUILD_CORE_SHADERS */

/* #undef RTSHADER_SYSTEM_BUILD_EXT_SHADERS */

#endif
